spring:
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            uri: mongodb://jkersey:BrendanSaulJames@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tlsAllowInvalidHostnames=true&retryWrites=false
            database: project2DB
    output:
        ansi:
            enabled: ALWAYS
    

