spring:
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            uri: mongodb://jkersey:BrendanSaulJames@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tlsAllowInvalidHostnames=true&retryWrites=false
            database: project2DB
    output:
        ansi:
            enabled: ALWAYS           
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 945516051025-n60et84sp07afmlhtmm3ksj114csm4vu.apps.googleusercontent.com
                        clientSecret: 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
                        scope: openid,email,profile