spring:
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            uri: mongodb://jkersey:BrendanSaulJames@jkersey-documentdb.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&tls=true
            database: project2DB
    output:
        ansi:
            enabled: ALWAYS
javax:
    net:
        ssl:
            trustStore: /tmp/certs/rds-trusttore.jks
            trustStorePassword: BrendanSaulJames

