spring:
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            uri: mongodb://jkersey:BrendanSaulJames@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tlsAllowInvalidHostnames=true&retryWrites=false
            database: project2DB
    output:
        ansi:
            enabled: ALWAYS
    security:
        filter:
            order: 10
jwt:
    secret: askldfjdsivohoawe420sdf2l34132wsfSDF231SDF231#5D&&SAAw12321ewdt543yh
