spring:
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            uri: mongodb://jkersey:BrendanSaulJames@jkersey-documentdb.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&tls=true&tlsCAFile=global-bundle.pem
    output:
        ansi:
            enabled: ALWAYS
    

