spring:
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            uri: mongodb://jkersey:<insertYourPassword>@jkersey-documentdb.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
    output:
        ansi:
            enabled: ALWAYS            
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 945516051025-n60et84sp07afmlhtmm3ksj114csm4vu.apps.googleusercontent.com
                        clientSecret: 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
                        # redirect-uri: http://localhost:8080/login/oauth2/code/google
                        # scope: openid,email,profile
javax:
    net:
        ssl:
            trustStore: /tmp/certs/rds-trusttore.jks
            trustStorePassword: BrendanSaulJames    

